# Lecture notes 10.4.2023

## Attributes & methods

An object in python has attributes and methods
- **attributes**: a property of an objec, a piece of info about it
- **method**: procedure associated with an objec, an action where the main ingredient is the object itself

Access a variables attributes and methods by adding a period at the end of the variable name

variable.variable_method() or 
variable.variable_attribute()

Examples:
Methods and attributes of numpy arrays

In [1]:
import numpy as np

In [4]:
# define a 3x3 array
var = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
print(var)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# shape: attributes telling us the number of elements in each dimmension of the array
var.shape

(3, 3)

In [6]:
type(var.shape)

tuple

In [11]:
# ndim an attribute holding the number of array dimmensions
var.ndim

2

In [12]:
type(var.ndim)

int

Attributes can have many different datatypes

In [14]:
# min
var.min()

1

In [17]:
type(var.min)

builtin_function_or_method

## R and Python

R:
- R doesnt use methods within an object
- Functions are extrinsic to outside the objects they are acting on

Example: recreate getting the min value in an array

In R, there would be 2 separate items: variable, var and a separate function, min, that gets var as a parameter

R code:
var <-- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
min(var)

Using pipe operator in R: this is closer to the . in python!
var <-- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
var %>% min()
(substitube the pipe for a period and then you get python code)

What is happening with the pipe?
Pipe passing the variable to the function as its first argument, this is essentially what the period does in python. 